spring:
  application:
    name: Microservice-Cloud
    
greeting-service:
  greeting: "Hola"
  default-value: "Mundo"
  
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'