spring:
  application:
    name: Microservice-Cloud
    
greeting-service:
  greeting: "Holaaaa"
  default-value: "Mundo, bien venido!"
  
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'